In [1]:
import pandas as pd

In [2]:
pd.DataFrame({'Yes': [50, 12], 'No': [131,2]})

   Yes   No
0   50  131
1   12    2

In [4]:
pd.DataFrame({'Bob' : ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland']}, index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.         Bland

In [5]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
pd.Series([30,35,40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [9]:
wine_reviews = pd.read_csv("wine_reviews.csv")

In [ ]:
wine_reviews.s